1) File "C:\Users\grand\Desktop\my_new_project\hello_flask\flask_mysql\mysql_connection\mysqlconnection.py", line 8, in __init__
  'database': bd, # we got db as an argument
NameError: global name 'bd' is not defined

2) File "C:\Users\grand\Desktop\my_new_project\venv\lib\site-packages\MySQLdb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'Jacob'@'localhost' (using password: YES)")

3) File "C:\Users\grand\Desktop\my_new_project\venv\lib\site-packages\MySQLdb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

4) File "C:\Users\grand\Desktop\my_new_project\venv\lib\site-packages\MySQLdb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (10061)")